### ISSUE TITLE
Website Problem

### ISSUE THREAD

**Issue by vaska94** [Bertrand31/Monitaure#11]
`Uncaught Error: Module build failed: Error: Cannot find module 'has'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/postcss-reduce-transforms/dist/index.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/cssnano/dist/index.js:41:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/css-loader/lib/loader.js:7:18)
    at Module._compile (module.js:571:32)
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/postcss-reduce-transforms/dist/index.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/cssnano/dist/index.js:41:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/css-loader/lib/processCss.js:16:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/monitaure/Monitaure/node_modules/css-loader/lib/loader.js:7:18)
    at Module._compile (module.js:571:32)
    at Object.<anonymous> (https://monitaure.io/app.js:15:23567)
    at t (https://monitaure.io/app.js:1:101)
    at Object.<anonymous> (https://monitaure.io/app.js:19:27255)
    at t (https://monitaure.io/app.js:1:101)
    at Object.<anonymous> (https://monitaure.io/app.js:14:4083)
    at t (https://monitaure.io/app.js:1:101)
    at Object.<anonymous> (https://monitaure.io/app.js:14:4993)
    at t (https://monitaure.io/app.js:1:101)
    at Object.<anonymous> (https://monitaure.io/app.js:12:5954)
    at t (https://monitaure.io/app.js:1:101)`

i get this error in console, while visiting https://monitaure.io/
i'm using Win10 + Chrome x64

**Comment by vaska94** [comment]
Manually visiting https://monitaure.io/app.js and refreshing it solved problem, you should disable caching for app.js in headers

**Comment by Bertrand31** [comment]
Thank you for raising the issue, although like you said the problem has been fixed you just had an old version of the code in you cache.
I might disable the cache on app.js in the future, I'll see.
