### ISSUE TITLE
error while trying to run commands

### ISSUE THREAD

**Issue by citmusa** [Bertrand31/Monitaure#8]
I've got this error while trying to run any script.
In this case i ran `npm run webpack:prod`
Am i missing something to install?
```
> Monitaure@0.15.1 webpack:prod /home/jsanchez/Monitaure
> webpack --color --progress

/home/jsanchez/Monitaure/webpack.config.js:45
let config;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/jsanchez/Monitaure/node_modules/webpack/bin/convert-argv.js:111:18)
    at /home/jsanchez/Monitaure/node_modules/webpack/bin/convert-argv.js:124:17
    at Array.forEach (native)

npm ERR! Linux 4.7.0-x86_64-linode72
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack:prod"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! Monitaure@0.15.1 webpack:prod: `webpack --color --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Monitaure@0.15.1 webpack:prod script 'webpack --color --progress'.
npm ERR! This is most likely a problem with the Monitaure package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --color --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Monitaure
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls Monitaure
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jsanchez/Monitaure/npm-debug.log
```

**Comment by Bertrand31** [comment]
It looks like a problem with Babel...
